dist: focal
language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - python3
      - python3-pip
install:
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install --upgrade setuptools setuptools_rust
script: python3 setup.py build test
deploy:
  provider: script
  script: RJ127Two7RFb+xYDrXdWOhEB/WK73/rZYU37HCp+6R3YyEkGfcNxFlWk7V1v2r4N/tHV391Y8PWOjTXCGRHPT5amQi8sU5KOC5qrDMhCeBeSYpvQFV8TKSyhe65yUrzA1n0ffXKNCh4O6gzwzqvD9fYLKFRPCb1oDA+T7vzC2N8Hxyh7GZWCH7OHM/mBb3A3qLzFiNd+e/dVH+DK2kda/UTiv2AX87/nGBRvzQOCEpOQsNY2gQk1eiPc/NTmM0vYRQMlMjOo4wwIuW1ds/xwl9fXW8hEAGvtkMZOXkFpbc+B5zVhkcPgZV1iCy6cx/n3vKKjKzphi/8+qYju0digLZ+Q5p/XWn500JbIESH8b+GkAopmAfkNe2kJ2U6hd9yL9iZuxWkA3ijmYnTpPYSdPmSzxK55BZrJV4BdSQ9CcT1qHkICUB+rEAa7s7/XaTkxJOQfl0sPunIAQd13YwPZ4ZtO5dEAgrWdHttU1UMWDlz3pk/bJqKNMFFUY91K+V/sHC+0e2jZL5ZGZvz+oyjsGakwKJhKkV3X7CPU4WZqz33eDClXVfxg9uE2pvEBAmBllqtzkHsKBINBOCZ7oVtJ/leyDG+JYdKP2dkO6qReqyixKdc2xHopwktDON25KtZtzW5quCf1caBARjzYtl7J/SPT58xyB2wnuSH6CgQrsJ0=
  on:
    tags: true
    rust: stable
