dist: focal
language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - python3
      - python3-pip
install:
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install setuptools_rust
script: source $HOME/.cargo/env && sudo python3 setup.py build test
deploy:
  provider: pypi
  user: platforme
  password:
    secure: eHZ1bC5+nqUUSYGWaFMiZcyI6qxmtVhaJpY/ZTBpjpvmFeSQVRUCj0vh9WTzcRdGEU5C0Iv0QyveDmZThEBQR5IE3YQqVniMLBpQFs1U0ZZ89u8d/QUFbqTrSJ+KxLLYDE5L8DkohXXa9WOQNP5tRk23bZguQDbJdNKR7n4YX8OIrsJKSe4hrCntgUq9NiJymocuHrn+h2sPLZZcHpZkG04CUATg9MEjv5sR20iKeIVX7DeFjKR23YWHtFukYLnzfbrIrEOwiL9UjvowdedVVFKypKnPqDKMOIy+VFqqpmbWvjF5Et5pjVssZvnYmvJZxRACpU9okZQnauk8k/9QsDmrFcY8n4ZSlBrzbny5KpjgxbmhvPPxhO43HBj1b39tJXRTONJa2XoBidY1i3lVyFoFhy9lCL/mAmxwHPLHNVz6UlW9JkfCV0EDS6WYRdb6V9HhG/jtXE6OFU3N6FPWBn5FTLXtcW5simgdLG6OgVUd/vUDk7st2t/jaeDZg7poPuD/kwk87i5FAX3zNYr2IYwcAruvtlTsHGOkWF9OllLKcZcMco8fdbH5DyncgVIv19hNxA/MTalvGVpkHtGZIZA1xukbTKY4ShOGMFhxzOJi3CvdO0J4PCs24KCxS/joCxNfLpwKc+2qYquQl3RtCxKpZeHfuIGmgZoyI0y4D4c=
  distributions: sdist bdist_wheel
  on:
    tags: true
    rust: stable
