dist: focal
language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - python3
      - python3-pip
install:
  - sudo pip3 install -r requirements.txt
  - sudo pip3 install --upgrade setuptools setuptools_rust
env:
  - secure: cS8WDjZDopZLZwkHg2ygz09ZzPWCNe369XbcrlLvfA1whyL6XqPgpsc59n7jFlDpGAdEpbV7yhSInTPq5PffqJg/cT2NM3bFKVr27v0BtkRXVbSJyDCaKt04297UoMAdl7VTFibJxauKB5IYaJNKWpXf9NVNDVL6nrad1fuw0EsOzzpqXMgjEg8bWD7cg6vfPE8a8z41fYaStfg+lNj1cfl81P5DKY/U4i5bTeOujs0y7YNpi6b8Hn6rpSFwD8MEGmmwizcFzRvxbJFiWQ9V2lo98D9A937zeXYuvG4o/o6xZ+4i73CRJPHlrngj30tEpDraRaH88HG4Dt6Tw7uGK+6vIyGq5lBJjxfXB+FT06fIZeWyo4wgJUdFbc9nhqyrSB8bpiWKyA13lntFxO9Zn0Jk2XeYyYmDxrqTjiu7pKOcc3jsLHI9zaJGUVRMLvdRIuXCLYWfkPr9QnTd4neqcK8UvyRMUKix3fCPqwY4hPst2hTuZbIhkueuoynUKfdXbKnbTIz3IXihH0A3yaBb0yira93Fy3ClmFGt2tD5dXhMTjYWaoO1qGBq3caSbCi9SrEAZ6RLVyD3s7jNvz66YU+NJ5W/cmxMzV9gNz687VcCHk7UDQelOcV0YfalGpWCcyHUUD8qlAbn9MVXY7K8WW4A9Ymc7gQ1TeX+4RmdRYg=
script: python3 setup.py build test
