name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build-crates:
    name: Deploy crates.io
    strategy:
      matrix:
        rust-version: ["1.40"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: |
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo publish --no-verify
  build-npm:
    name: Deploy NPM
    strategy:
      matrix:
        rust-version: ["1.40"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: node --version
      - run: cargo install wasm-pack
      - run: |
          wasm-pack build --release --target=nodejs -- --features wasm-extension
          wasm-pack build --release --target=bundler --out-name pconvert_rust_bundler  -- --features wasm-extension
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          cd pkg && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  build-pypi:
    name: Deploy PyPI
    strategy:
      matrix:
        rust-version: ["1.40"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: cargo build --features python-extension
      - run: PYTHON3="${pythonLocation}/bin/python3" PIP3="${pythonLocation}/bin/python3 -m pip" ./deploy.sh
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
