name: Main Workflow
on: 
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57", "1.58", "1.59", "1.60", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo test
      - run: cargo build
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
  build-complete:
    name: Build Complete
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57", "1.58", "1.59", "1.60", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo test
      - run: cargo build --features wasm-extension
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
      - run: cargo doc --lib --all-features
  build-python:
    name: Build Python
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57", "1.58", "1.59", "1.60"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}-bullseye
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: PYO3_PYTHON="${pythonLocation}/bin/python3" cargo build --features python-extension
      - run: cargo run version
      - run: ${pythonLocation}/bin/python3 -m pip install --upgrade .
      - run: ${pythonLocation}/bin/python3 setup.py test
