name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.61", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo test
      - run: cargo build
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
  build-complete:
    name: Build Complete
    strategy:
      matrix:
        rust-version: ["1.61", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo test
      - run: cargo build --features wasm-extension
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
      - run: cargo doc --lib --all-features
  build-python:
    name: Build Python
    strategy:
      matrix:
        rust-version: ["1.61"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}-bullseye
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.8
        run: |
          apt update
          apt-get install -y software-properties-common 
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get install -y python3.8
          ln -s `which python3.8` /usr/local/bin/python
      - run: PYO3_PYTHON="${pythonLocation}/bin/python3" cargo build --features python-extension
      - run: cargo run version
      - run: ${pythonLocation}/bin/python3 -m pip install --upgrade .
      - run: ${pythonLocation}/bin/python3 setup.py test
