name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.40", "1.46", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
