name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.46", "1.47", "1.48", "1.49", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - run: cargo build
      - run: cargo test
      - run: PYO3_PYTHON="${pythonLocation}/bin/python3" cargo build --features python-extension
      - run: cargo build --features wasm-extension
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
      - run: cargo doc --lib --all-features
      - run: LD_LIBRARY_PATH="${pythonLocation}/lib" ${pythonLocation}/bin/python3 -m pip install --upgrade .
      - run: LD_LIBRARY_PATH="${pythonLocation}/lib" ${pythonLocation}/bin/python3 setup.py test
