name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.40", "1.45", "1.46", "1.47", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: ls -la ${pythonLocation}
      - run: ls -la ${pythonLocation}/bin
      - run: ${pythonLocation}/bin/python3 -m pip install --upgrade .
