name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.61", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo run version
      - run: cargo test
      - run: cargo build
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
  build-complete:
    name: Build Complete
    strategy:
      matrix:
        rust-version: ["1.61", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo run version
      - run: cargo test
      - run: cargo build --features wasm-extension
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
      - run: cargo doc --lib --all-features
  build-python:
    name: Build Python
    strategy:
      matrix:
        rust-version: ["1.61"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: apt update && apt-get install -y -q python3.9 python3-pip
      - run: cargo run version
      - run: cargo build --features python-extension
      - run: python3 -m pip install --upgrade .
      - run: python3 setup.py test
