name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.40", "1.45", "1.46", "1.47", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - run: cargo build
      - run: cargo build --features python-extension
      - run: cargo build --features wasm-extension
      - run: cargo run version
      - run: cargo run benchmark assets/demo/
      - run: cargo run benchmark assets/demo/ --parallel
      - run: cargo doc --lib --all-features
