name: Wasm Workflow
on: 
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57", "1.58", "1.59", "1.60", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: node --version
      - run: cargo install wasm-pack
      - run: npm install
      - run: npm test
      - run: wasm-pack build --release --target=nodejs -- --features wasm-extension
