name: Wasm Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.46", "1.47", "1.48", "1.49", "1.50", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: node --version
      - run: cargo install wasm-pack
      - run: npm install
      - run: npm test
      - run: wasm-pack build --release --target=nodejs -- --features wasm-extension
